version: '3'
services:
  home-automation:
    image: niecore/home-automation:latest
    restart: unless-stopped
    environment:
      - HOMEASSISTANT_HOST
      - HOMEASSISTANT_PORT
      - HOMEASSISTANT_TOKEN